# Generated by Django 4.1.2 on 2022-11-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bawjobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bawjobs',
            name='password',
        ),
        migrations.RemoveField(
            model_name='bawjobs',
            name='user',
        ),
        migrations.AddField(
            model_name='bawjobs',
            name='ipm_project_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bawjobs',
            name='ipm_project_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bawjobs',
            name='ipm_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
