# Generated by Django 4.1.1 on 2022-11-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bawjobs', '0002_remove_bawjobs_password_remove_bawjobs_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bawjobs',
            name='ipm_project_name',
        ),
    ]
